# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Continuous Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 6'

concurrency:
  group: ${{format('{0}:{1}', github.repository, github.ref)}}
  cancel-in-progress: true

jobs:
  beman-submodule-check:
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-submodule-check.yml@1.7.4

  preset-test:
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-preset-test.yml@1.7.4
    with:
      matrix_config: >
        [
          {"preset": "gcc-debug", "image": "ghcr.io/bemanproject/infra-containers-gcc:latest"},
          {"preset": "gcc-release", "image": "ghcr.io/bemanproject/infra-containers-gcc:latest"},
          {"preset": "llvm-debug", "image": "ghcr.io/bemanproject/infra-containers-clang:latest"},
          {"preset": "llvm-release", "image": "ghcr.io/bemanproject/infra-containers-clang:latest"},
          {"preset": "msvc-debug", "runner": "windows-latest"},
          {"preset": "msvc-release", "runner": "windows-latest"}
        ]

  catch-test:
    permissions:
      actions: read
    strategy:
      fail-fast: false
      matrix:
        platform:
          - description: "GNU 14"
            compiler: "gcc:14"
            toolchain: "infra/cmake/gnu-toolchain.cmake"
          - description: "LLVM 19"
            compiler: "clang:19"
            toolchain: "infra/cmake/llvm-toolchain.cmake"
          - description: "Windows MSVC"
            os: windows-latest
            toolchain: "infra/cmake/msvc-toolchain.cmake"
          #- description: "Macos Appleclang"
          #  os: macos-latest
          #  toolchain: "infra/cmake/appleclang-toolchain.cmake"
        cpp_version: [20, 23, 26]
        cmake_args:
          - description: "Default"
          - description: "TSan"
            args: "-DBEMAN_BUILDSYS_SANITIZER=TSan"
          - description: "MaxSan"
            args: "-DBEMAN_BUILDSYS_SANITIZER=MaxSan"
        include:
          - platform:
              description: "GCC 14"
              compiler: "gcc:14"
              toolchain: "infra/cmake/gnu-toolchain.cmake"
            cpp_version: 20
            cmake_args:
              description: "Werror"
              args: "-DCMAKE_CXX_FLAGS='-Werror=all -Werror=extra'"
          - platform:
              description: "GCC 14"
              compiler: "gcc:14"
              toolchain: "infra/cmake/gnu-toolchain.cmake"
            cpp_version: 20
            cmake_args:
              description: "Dynamic"
              args: "-DBUILD_SHARED_LIBS=on"
        exclude:
          # MSVC does not support sanitizers with VCPKG!
          - platform:
              description: "Windows MSVC"
            cmake_args:
              description: "TSan"
          - platform:
              description: "Windows MSVC"
            cmake_args:
              description: "MaxSan"

    name: "Unit:
      ${{ matrix.platform.description }}
      ${{ matrix.cpp_version }}
      ${{ matrix.cmake_args.description }}"
    runs-on: ${{ matrix.platform.os || 'ubuntu-latest' }}
    container:
      image: ${{ matrix.platform.compiler && 'ghcr.io/bemanproject/testingcontainers-' }}${{ matrix.platform.compiler }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        if: ${{ !matrix.platform.compiler }}
        uses: ./.github/actions/setup-environment
      - name: Build and Test
        uses: ./.github/actions/cmake-build-test
        with:
          cpp_version: ${{ matrix.cpp_version }}
          toolchain_file: ${{ matrix.platform.toolchain }}
          cmake_extra_args: ${{ matrix.cmake_args.args }}

  configuration-test:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bemanproject/testingcontainers-gcc:14
    strategy:
      fail-fast: false
      matrix:
        args:
          - name: "Disable build testing"
            arg: "-DBEMAN_BOUNDS_TEST_BUILD_TESTS=OFF"
          - name: "Disable example building"
            arg: "-DBEMAN_BOUNDS_TEST_BUILD_EXAMPLES=OFF"
          - name: "Disable config-file package creation"
            arg: "-DBEMAN_BOUNDS_TEST_INSTALL_CONFIG_FILE_PACKAGE=OFF"
    name: "CMake: ${{ matrix.args.name }}"
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        uses: ./.github/actions/cmake-build-test
        with:
          cpp_version: 20
          toolchain_file: "infra/cmake/gnu-toolchain.cmake"
          cmake_extra_args: ${{ matrix.args.arg }}
          disable_test: true

  compiler-test:
    permissions:
      actions: read
    strategy:
      fail-fast: false
      matrix:
        compilers:
          - class: gcc
            version: 14
            toolchain: "infra/cmake/gnu-toolchain.cmake"
          - class: clang
            version: 20
            toolchain: "infra/cmake/llvm-toolchain.cmake"
          - class: clang
            version: 19
            toolchain: "infra/cmake/llvm-toolchain.cmake"
          - class: clang
            version: 18
            toolchain: "infra/cmake/llvm-toolchain.cmake"
          - class: clang
            version: 17
            toolchain: "infra/cmake/llvm-toolchain.cmake"
    name: "Compiler: ${{ matrix.compilers.class }} ${{ matrix.compilers.version }}"
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/bemanproject/testingcontainers-${{ matrix.compilers.class }}:${{ matrix.compilers.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        uses: ./.github/actions/cmake-build-test
        with:
          cpp_version: 20
          toolchain_file: ${{ matrix.compilers.toolchain }}

  create-issue-when-fault:
    needs: [preset-test, catch-test, configuration-test, compiler-test]
    if: failure() && github.event_name == 'schedule'
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-create-issue-when-fault.yml@1.7.4
